[project]
name = "virtual-tailoring"
version = "1.0.0"
requires-python = ">=3.11,<3.12"

[tool.setuptools]
py-modules = []

[build-system]
requires = ["setuptools>=65.0.0", "wheel"]
build-backend = "setuptools.build_meta"

